### ISSUE TITLE
Please tell how to set chests to spawn items

### ISSUE THREAD

**Issue by iRalCraft** [SkyWars/SkyWars#102]
Hello,
could you please tell me how i can make the chests on MY SELF CREATED skyward map actually spawn items.
Also please tell me how to make the chests spawn in different items.
Thank you a lot if you are willing to help!
Felix berendes.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I'll help more.
