### ISSUE TITLE
Self killing bug

### ISSUE THREAD

**Issue by Gaurav99** [SkyWars/SkyWars#124]
Hey,

Whenever I jump into the void, this happens
http://i.gyazo.com/55c038a988ffd18843ed05bfcdb0a2df.png
And I do get score and money.

Thanks

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work - this should be fixed as of https://github.com/SkyWars/SkyWars/commit/2c2fe6bd522744df72d3b99ccf562abf75ab9aa3.
