### ISSUE TITLE
New arena setup

### ISSUE THREAD

**Issue by laksida** [SkyWars/SkyWars#132]
Hello, i'm tryna setup a new skywars map but the old one keeps coming up i got no errors though

spigot-1.7.10-R0.1-SNAPSHOT.jar
version skywars; R: v2.0.0 for CB 1.7.9-R0.1 Jul 20, 2014

Erhm i did this

Use /sws start <name you want> to start setting up an arena. Replace <name you want> with a name that you think would fit your new arena.
Generally this should be all lower-case and contain only 0-9, a-z and -.

Stand at one of the corners of the arena, so that your head is at the very edge of the arena on 3 sides.
At that position, use /sws setpos1. This probably will require flying, as you need to be outside of the arena.

Stand at the corner opposite the corner you just stood at. Then use /sws setpos2

Go to every place where a player should spawn, and use /sws addspawn.

When you have added all the spawns you want, use /sws save to save your arena. This will create a .yml file in the plugins/SkyWars/arenas folder.

If you want to enable teams, or have a different number of players in the game than spawns there are, you should edit the plugins/SkyWars/arenas/<arena name>.yml file. You can enable teams by changing team-size to something other than 1.

Enable the arena in main-config.yml. This can be done by adding the arena name that you used in step 1 to the enabled-arenas list.

- my config folder; ; http://pastebin.com/5dnuBL3a

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. Closing this as it seems to be fixed, or not an issue with SkyWars.
