### ISSUE TITLE
Join Signs

### ISSUE THREAD

**Issue by RobinHood3** [SkyWars/SkyWars#133]
(Feature)
Hey, I really would like to have join signs instead of a portal queue.
How should this maybe work? 
I set a number of arenas in the config and I can make as many signs as the arenas I set there or I can make a few and when it's starting let it rotate and make a new arena.

I think the plugin would be even better if you do this.

**Comment by daboross** [comment]
Implemented now! Will be released with SkyWars v2.1.4. Documentation: https://dabo.guru/projects/skywars/signs-and-portals.
