### ISSUE TITLE
Automatic chest fill and refill.

### ISSUE THREAD

**Issue by RobinHood3** [SkyWars/SkyWars#134]
Hey,
This would also be a useful feature, to have a random refill of chests.
So configured in the config items with levels of appearing rate.
Each time a new arena is created fill the chest with other items.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to close this now as a duplicate of https://github.com/SkyWars/SkyWars/issues/117. If you still use SkyWars, continue discussion there!
