### ISSUE TITLE
/sws   --bug--

### ISSUE THREAD

**Issue by killer92scw** [SkyWars/SkyWars#136]
v2.0.0 for CB 1.7.9-R0.1 Jul 20, 2014

when i try to make my own arena it tells me "Spawn point set".
when i do any of the /sws commands it all says the same thing "Spawn point set".
i did /sws save, and it said "Spawn point set".
 
please get back to me idk if its something im doing wrong or a bug.

         Thank you,
                    Killer92scw.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I will investigate further.
