### ISSUE TITLE
Previous maps/games not clearing or overlapping

### ISSUE THREAD

**Issue by jaxmacky** [SkyWars/SkyWars#137]
I installed 2.0 and let it generate all new configs.  I have two maps set up in different worlds centered at 0,0, x&z. Both arenas were set up with the same size cuboid, both with 8 spawn points.  The problem I am having is in-game/maps are overlapping. Almost like the previous game/map was not cleared in the skywarsarenaworld before the new game/map is added. I also get random items laying in a new map/game, from previous player deaths. Setting the "arena-distance-apart:" to different intervals, did not seem to fix this.
Link to my SkyWars Report:  http://is.gd/aabSKs
Link to screenshot of overlapping: http://imgur.com/ljdhhPq  Cobblestone Tower does not belong to this map.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work - this should be fixed as of https://github.com/SkyWars/SkyWars/commit/73d2f8bffbfd1ae34d8b98d9d78aaf4596a2ca6a.
