### ISSUE TITLE
Can't enchant non-enchantable items (Knockback on Stick)

### ISSUE THREAD

**Issue by Gaurav99** [SkyWars/SkyWars#142]
http://pastebin.com/y5pkGcQd
This happened when a game started on my server.  Doesn't happen every time, just randomly saw it in my console.  I'm using SkyWars 2.0.1-Snapshot and Spigot version 1604.

Thanks

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

This should be fixed as of SkyWars/SkyWars-API@0df0371.
