### ISSUE TITLE
Arenas not created as planned.

### ISSUE THREAD

**Issue by SimonBird883** [SkyWars/SkyWars#150]
I having a issue here.. 
http://imgur.com/UcHWxLB

The picture explains everything. There are also items at one of the islands, I hope u would look at this, all my player love this ;D!

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I will investigate further.

**Comment by SimonBird883** [comment]
My server closed for a while ago, but your version of SkyWars is unique and I love it for that, so ofcourse I will still use this plugin if its updated :+1: I am currently re-building my server from scratch, and sure SkyWars will come again :)

**Comment by daboross** [comment]
Awesome! I think this bug has probably been fixed, but it might still exist as I haven't been able to reproduce it. If you run into it again, please do tell me! :)
