### ISSUE TITLE
Plugin wont load

### ISSUE THREAD

**Issue by ferengi4** [SkyWars/SkyWars#152]
Added latest version to a 1.7.10 pixelmon server and it never loaded. Dunno what to do.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I will investigate further.
