### ISSUE TITLE
Arena Configuration

### ISSUE THREAD

**Issue by chickenputty** [SkyWars/SkyWars#156]
I've read through this: https://dabo.guru/projects/skywars/creating-an-arena but, I am still confused about a few things.

When is "arena-parent.yml" used?
What do the origin, building, and clearing boundaries signify?

By the way, I stumbled around in the github wiki that appears to be valid, but hasn't been updated on a second look. I would suggest removing it if there is no intention on updating it. (https://github.com/SkyWars/SkyWars/wiki/Commands-and-Permissions)

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I believe this was just a question though which has been answered, so closing.
