### ISSUE TITLE
Players being bombarded with health potions at beginning of game

### ISSUE THREAD

**Issue by SarahJaneSmith** [SkyWars/SkyWars#163]
Hi,

Runntine Centos 6, MC 1.7.10, SkyWars 2.0, Java 7. The pluging was working great until the arena was moved. The recreated arena allows players to start the game, get to the lobby & spawn in the glass boxes. When the game starts player1 is bombarded with health potions & cannot see to play. Player2 is moved outside the glass box and levitated to spawn1 & placed in with player1. Suggestions as we are unable to play at this point. I have recreated the setup again, same results. restarted the server, same issue. There are no errors on the console whatsoever. Thanks!

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume that, after being abandoned, you are either no longer using SkyWars. Reply if otherwise.

**Comment by SarahJaneSmith** [comment]
i would if i could get it to run, i absolutely love that app/game

**Comment by daboross** [comment]
I did release SkyWars 2.0.1 recently, it might help fix the issue you are having if you do still want to use SkyWars.

**Comment by SarahJaneSmith** [comment]
oh! cool, i will check it out.. thanks :)

**Comment by daboross** [comment]
No problem!

I'm going to close this issue for now, as I don't *think* it exists in the latest version. If you get back using SkyWars again and still experience this issue, just reply and I will re-open and help further!
