### ISSUE TITLE
Possible to join SkyWars from Hunger Games / other plugins + minimum player count / countdown

### ISSUE THREAD

**Issue by MithrandirCraft** [SkyWars/SkyWars#164]
Server version: Spigot for 1.7.10
Plugin version: 2.0.0

Before explaining some of the bugs I have encountered, I would like to clarify that my server is not a network, and that yur skywars plugin coexists inside my server whith other plugins like Factions, Hunger Games, and Prop Hunt. If your plugin was meant only for networks, being on a server of it's own, please clarify this in the plugin description, if not, I would appreciate a lot if these errors could be fixed :) Thanks!

Encountered bugs/issues, and some suggestions:

- External experience is brought inside the arena, this makes enchanting inside skywars a bit of a joke, if you bring experience from outside. And it also makes it unfair for players who want to maintain their experience. Just like the external inventory is saved before entering a skywars game, I think the experience should too.

- I haven't tested this, but I'm thinking it's provably possible to join Hunger Games, while in a skywars cue. I do not know what can happen in such a situation. I'm also thinking that joining skywars is a good way to get teleported away from an unwanted pvp in Factions. But still it doesn't look like a perfect way, as the games don't usually start inmediately. In order to avoid these two similar issues I would suggest having separate permissions for joining via command, and entering the portal, that way I could forbid distance joining, and permit portal joining. (I'm not entirely sure if this is already a possible thing to do, so I will be testing. Please tell me if there is already a way.)

- There's no way to configure the default player minimum ammount required to start a game. (Or maybe I'm skipping it, but I definetly can't find it)

- There's no countdown for the game to start. I would suggest a countdown during wich you can't move, or break anything inside the arena, this would work perfectly when combined whit the minimal player ammount required for starting the game. The game would wait about 10 seconds, before starting whith the minimal ammount, during this time, it would give more players a chance to join the game.

- A visual GUI for kit selection at start of game would be much better than just a command. Consider adding this :)

I might be editing this ticket and adding any more issues I encounter. Your plugin is very close to being the best, and most updated Skywars Plugin to date :) I personally think that whith my suggestions and corrections It will definetly be the best :D

**Comment by MithrandirCraft** [comment]
I've managed to solve the first issue myself whith the multiinv plugin.

However, untill a new feature which enables the configuration of chest content, I don't think I will be using SkyWars

**Comment by daboross** [comment]
My extreme apologies for not answering anything here, and for abandoning the project for the longest time. I'm not completely back, but there are a few people working on new features who want to take over the project, and I'm doing some stuff to clean it up.

Experience being brought in has been fixed, and minimum player count will be added. With the chest control, the main way you'd have to do it is just copy the main arena into a custom arena, and edit the chests in game. I can try and add a guide to do that.

If you still use SkyWars, (I doubt many people do after I abandoned it), I'll be working on these things. For translating, if you would want to help, or if anyone else who is looking at this does, there's a guide at https://github.com/SkyWars/SkyWars-Translations/wiki/Translating.

**Comment by daboross** [comment]
For the hunger games, I'm unsure exactly how that plugin works, but I think it should be possible to use your permissions plugin to remove the skywars.join permission in the world in which Hunger Games games are played.

**Comment by MithrandirCraft** [comment]
Hello. I appollogize, but I stopped using this plugin due to inactivity, and the fact that my server just couldn't manage so many game modes.

My server is much simpler now, and it's better for my money and mental health xD

In any case, thank you for answering. Feel free to close this ticket.

**Comment by daboross** [comment]
No problem! I didn't really expect that many people would still be using it at this point, especially with my abandoning it!

Thank you for the reply! I guess I will close this ticket and keep https://github.com/SkyWars/SkyWars/issues/99.
