### ISSUE TITLE
Problem Skywars

### ISSUE THREAD

**Issue by rubencrz** [SkyWars/SkyWars#166]
Hello good , the plugin gives me an error, ie non- console game but a player who does not have OP does not let you interact with anything ... do not let him break anything, or use sword , nothing seems GroupManager failure but I'm tired of searching and can not be , I hope your reply Thanks rubencrz09@gmail.com

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume that, after being abandoned, you are either no longer using SkyWars. Reply if otherwise.
