### ISSUE TITLE
A new feature?

### ISSUE THREAD

**Issue by LassiP** [SkyWars/SkyWars#168]
Could you do so, as this plugin works only in skywars world(s) So as it doesn't complicate anything that is in same server, but different worlds?
That would really be useful, as example: My server has minigames and survival playing. Sometimes this complicates survival playing because this has features that work even in my survival world.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

There are new features in the latest build to help with isolation should function correctly, and it is also possible to change permissions per world with your permissions plugin.
