### ISSUE TITLE
Plugin is invisible to server

### ISSUE THREAD

**Issue by NLGamingEnzo** [SkyWars/SkyWars#171]
I put the server in the plugins folder but the plugin is invisible to the console/server.
Can someone please help me?

**Comment by NLGamingEnzo** [comment]
Hey Dabo Ross,

Sorry but it Crasht, When i was playing on my server (i forgot to email you
sry) it crasht and when i fixed it the Skywars plugin was missing (with
some others) i tried to download it again and put it in my plugins folder
but it crashes when i put it out the server works. So sorry i dont need you
anymore (is this the nice way to say it? sry if it isnt)[?]

**Comment by daboross** [comment]
It's fine, I'll close this issue then.

**Comment by NLGamingEnzo** [comment]
ok! thx anyway!

2015-01-02 22:29 GMT+01:00 Dabo Ross <notifications@github.com>:
