### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by Faller10** [SkyWars/SkyWars#174]
Hi!
So, I am hours trying to make an arena but i'm not getting it right! I really enjoyed this plugin, but I have problems understanding it! Could someone help me, with a video or with a nice explanation? I follow all the steps in the plugin "SETTING UP AN ARENA" category, but I still don't get it right! And i didn't find any youtube videos on this plugin! 
Much Aprecciated! 
Thanks!

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm going to assume that since the project has been abandoned for so long, that you moved to another project.

If you do still use SkyWars, just reply again to this issue and I will re-open and help.
