### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Faller10** [SkyWars/SkyWars#175]
For some reason after me and my friends play 1 game in the second one I use forcestart to begin and we are not teleported to the default arena and even when we type /sw leave after it keeps saying that we are in-game and if we try to make /sw leave another time it gives me console errors!
Thanks!

Console erro in 2nd attempt of /sw leave:
http://pastebin.com/6z9wrRMT

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work - this should be fixed as of https://github.com/SkyWars/SkyWars/commit/9939d32fd54202ca0d9dd39f64816acaa8f8ecc1.
