### ISSUE TITLE
Commands don't work at all

### ISSUE THREAD

**Issue by FastHead** [SkyWars/SkyWars#176]
Dear dabroross,

When I type /sw join or /sw help or whatever I type, nothing happens. Everything has been disabled and I can't do anything.
I hope you can help as fast as possible, because this is a big problem for my server.

Kind regards

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I'll help more.
