### ISSUE TITLE
Instant fall from the map

### ISSUE THREAD

**Issue by FastHead** [SkyWars/SkyWars#178]
Dear devolper,

When the skywars starts on the self maded map, you instantly fall from the map and don't even be for a second on a platform

How to fix this?

Kind regards

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I'll help.
