### ISSUE TITLE
SkyWars error on startup

### ISSUE THREAD

**Issue by NDruce** [SkyWars/SkyWars#179]
http://pastebin.com/tM4NE7VH

**Comment by FabioZumbi12** [comment]
This is because the version code need to check if is null (on code)! Wait daboross to fix this!

**Comment by iBars** [comment]
I just fixed it myself and was convinced about it is not plugin that I need (I use WickedSkyWars now)

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. Since this seems to be fixed in the latest release, closing.
