### ISSUE TITLE
Randomize Chests

### ISSUE THREAD

**Issue by quack123456** [SkyWars/SkyWars#180]
How do i make it so i can have chests randomize different materials or do i have to put them in after every match?

**Comment by quack123456** [comment]
Bump

**Comment by quack123456** [comment]
bump

**Comment by daboross** [comment]
no way currently

**Comment by quack123456** [comment]
ah so i have to put them in after every match

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to close this now as a duplicate of https://github.com/SkyWars/SkyWars/issues/117. If you still use SkyWars, continue discussion there.
