### ISSUE TITLE
SkyWars - big issue

### ISSUE THREAD

**Issue by 43Rockstarr** [SkyWars/SkyWars#182]
Version 2.0.0
/sw report: http://is.gd/9kiidG
server.log errors: https://gist.github.com/afc8d80f0f2a5ff3cdb1.git
When I try to start a game (with two players in queue), it says started but takes the players no where. If I stop it, it stops, but it thinks the players are still in the game when there isn't even a game running. This keeps them from doing commands, etc. and never lets them join a game until reloaded. If you check the status, nothing is running, if you closeall, nothing happens. If this could get fixed I'd really appreciate it, I really need the plugin for my server. Thank you!

**Comment by 003mikey** [comment]
Do you have donator kits set up? with permissions?

**Comment by 43Rockstarr** [comment]
All the permissions are given and I haven't done anything with kits, they are as they were when I first downloaded the plugin.

**Comment by 003mikey** [comment]
Do you know how to make a costly donator kit?

**Comment by 43Rockstarr** [comment]
Not sure. I just got this plugin. If I made a kit with it I'm guessing I could figure it out, what do you mean by the "costly" part?

**Comment by 003mikey** [comment]
I just mean if you could make a donator kit that cost IG points to get, and requieres a permission. If you figure out how to make me one, ill help you with your problem :)

**Comment by 43Rockstarr** [comment]
I can't work know it tonight, I'll do it tomorrow and reply to this and let you know I'm ready. Thank you!

**Comment by 003mikey** [comment]
Wow, thank you, you dont know how long I've been looking for an answer.

**Comment by 003mikey** [comment]
Did you find a answer to my problem?

**Comment by 43Rockstarr** [comment]
Not yet, haven't had a chance to work on anything yet, tons of school stuff to do. Will figure it out eventually, not sure when I'll have the chance for you to show me though :(

**Comment by 003mikey** [comment]
As long as you show me how to make the specific kit I asked you for, Ill make it happen for you.

**Comment by 003mikey** [comment]
anything yet?

**Comment by 43Rockstarr** [comment]
nope, too busy. won't be able to until this weekend

**Comment by 003mikey** [comment]
Once you work on it msg me

**Comment by 003mikey** [comment]
????

**Comment by 43Rockstarr** [comment]
Still too busy, sorry.
