### ISSUE TITLE
Points system

### ISSUE THREAD

**Issue by Ssensaxs** [SkyWars/SkyWars#186]
Having point system as Skywars-plugin plugin that was abandoned.

http://dev.bukkit.org/bukkit-plugins/skywars-plugin/

**Comment by daboross** [comment]
Unfortunately, this project was also abandoned. :(

SkyWars does have a points system, but not a complete one.

**Comment by daboross** [comment]
Closing this as a semi-duplicate of https://github.com/SkyWars/SkyWars/issues/69.
