### ISSUE TITLE
Skywars gets disabled immediately [1.7.10]

### ISSUE THREAD

**Issue by Siebe16** [SkyWars/SkyWars#187]
Hi,

Im moderator on a server, and every time the server gets reloaded SkyWars always turns red in /pl list. The server is running on 1.7.10 and we use SkyWars 2.0.0.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I will investigate further.
