### ISSUE TITLE
SkyWars points

### ISSUE THREAD

**Issue by Pixuu** [SkyWars/SkyWars#188]
Hi!

You have great plugin over here but is there a possibility to show person points somehow? I have not found any answer for that. If not, can you add that?

**Comment by daboross** [comment]
It's currently possible by adding `{SKYWARS.USERPOINTS}` to the chat format.

**Comment by Pixuu** [comment]
Great! That hasn't been written to wiki? And can I somehow convert SQLite to MySQL?

**Comment by daboross** [comment]
I think it's somewhere in the wiki, not sure where though.

SkyWars doesn't use SQLite at all, so I don't think it would be possible to convert SQLite data to MySQL.

**Comment by Pixuu** [comment]
Playerdata uses some kind of sql database to save players score?

"56d7e90d-5b4e-4579-8f77-6174a71ea87c":{"username":"Pix3li","score":1069}

I remembered that there was option to save those to MySQL but I think now not.

  sql:
    host: 127.0.0.1
    port: 3306
    database: minecraft
    username: root
    password: aComplexPassword

Problem is maybe when there is many players and it loads from sql file but this time there is not any problem, thanks! :+1:
