### ISSUE TITLE
Skywars Malfunction

### ISSUE THREAD

**Issue by TCNServer** [SkyWars/SkyWars#197]
My skywars plugin isn't working. Any solutions?

**Comment by daboross** [comment]
Probably! What problems are you having?

**Comment by TCNServer** [comment]
It's showing as Red when I do /pl, and I need this plugin to work sometime soon

Sent from my Windows Phone
________________________________

**Comment by daboross** [comment]
Ok! Could you attach your server log file from when the server started up? That will help me debug what's happened / what's wrong.

It should work just to drag the file into the comment box on https://github.com/SkyWars/SkyWars/issues/197 when you next have access to your server.

**Comment by daboross** [comment]
Hi!

There was recently a release of SkyWars v2.1.1 which fixes a bug where the plugin wouldn't work at all on Windows. Without any more information from your case, I'm going to assume that the update fixed your crash as well.

If you are still having trouble with the plugin after the 2.1.1 update, please reply and I will re-open the issue and provide more assistance!
