### ISSUE TITLE
Unable to Update Arena with /sws update-arena <Name>

### ISSUE THREAD

**Issue by Gnarusly** [SkyWars/SkyWars#202]
When I type /sws update-arena <Name>, it says that there are too many arguments.

For example, /sws update-arena defaultarena will return that there are too many arguments.

Server Version:

http://is.gd/vX8IFu

Output url from `/sw report`:

There are no errors in console.

**Comment by daboross** [comment]
let me look into this

**Comment by daboross** [comment]
Yep, this was an idiotic mistake I made. This will be fixed next version!
