### ISSUE TITLE
Players do not teleport to arena

### ISSUE THREAD

**Issue by ItsPepper** [SkyWars/SkyWars#208]
#### Issue / Bug / Crash:Players do not teleport to the arena when the game "starts"

Server Version: 1.8.8 but has a plugin to allow 1.9 clients

When did this issue occur?: Since I downloaded the plugin

What did you expect to happen?:Game starts, teleports players in

What happened?:Nothing

Output url from `/sw report`:http://is.gd/xNYuCo

Any errors in console?:Yea, something about Arena water-warriors not loaded.

#### Feature Request:

What would you like to be added?:

**Comment by daboross** [comment]
Could you upload a zip of your server log? One that includes the startup and when players have all joined.

**Comment by ItsPepper** [comment]
Sure, here is one where it shows joining, loading, closing, except in this load file it is the other default map

**Comment by ItsPepper** [comment]
No longer needed - hired a dev to just code a custom one thx anyway

**Comment by daboross** [comment]
Ok, closing then.
