### ISSUE TITLE
Could not pass event PlayerInteractEvent to SkyWars

### ISSUE THREAD

**Issue by StalKlim** [SkyWars/SkyWars#215]
Bug. Server Version: spigot 1.8.8-R0.1 I can't say for sure, but I have noticed this error in the console, then when the game begins in the arena. I need help to correct this error, so that it did not appear in the console and does not lead to disruptions on the server and arenas SkyWars. SW report http://prntscr.com/bin6yh Error http://pastebin.com/frfv7p97

**Comment by daboross** [comment]
OK, thank you for reporting this!

In the server log error, I think there should be around 5 more lines below what's in the pastebin. Could you possibly make another pastebin with 5 more lines included above and below the error?

**Comment by StalKlim** [comment]
Yes of course. Found here is such an interesting piece in the logs where the error is in the error. http://pastebin.com/Kk9JHqRj

**Comment by daboross** [comment]
Ok, I think I might have a possible reason.

Could you try this dev build, and report if it fixes it?

[SkyWars-v2.1.6-dev.zip](https://github.com/SkyWars/SkyWars/files/326458/SkyWars-v2.1.6-dev.zip)

**Comment by StalKlim** [comment]
Over the last 4 days of using the plugin not found any problems, thank you)

**Comment by daboross** [comment]
Awesome, thank you for reporting this! I'll release this as a bugfix version after fixing a few other things.
