### ISSUE TITLE
Starting a game without the maximum amount of players

### ISSUE THREAD

**Issue by NintendoFrosty** [SkyWars/SkyWars#221]
#### Feature Request:

What would you like to be added?:
In order to start a game, it seems that only the maximum amount of players is required for a game to begin. Right now, we would like to use an 8 player map, which we have ready. However, we need all 8 players to join in, just to start.

Of course there is forcestart by an admin, but we are looking for a way normal players can start when there is about 4 players, or any other set minimum amount of players. 
Possibly when a set minimum players join, a countdown starts, giving more players time to join if there are (Possibly even giving time for players to quickly pick out a kit), and if not, the game starts anyway, without needing the maximum amount of players, or an admin.

4 player maps seem a bit too small for us, if more players wanted to join in on the fun, so we're hoping for a feature like this, where any number of players can join a game, without restricting to a group that's too small, or just not enough players.

(If this is somehow already a feature, or something similar, I'm struggling to find it anywhere in the config.)

Thank you for your time!

-NintendoFrosty

**Comment by daboross** [comment]
Hi, thank you for the request!

This is currently being added, as part of the "start timer" feature. It isn't available yet, but will be released in the next feature release. Most of it is done now, I just haven't been able to get to my main computer to run the full set of scenario tests on the version before releasing it.

**Comment by daboross** [comment]
Implemented in v2.2.0!
