### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bri601** [SkyWars/SkyWars#222]
#### Issue / Bug / Crash:

Server Version:1.9.4

When did this issue occur?:It's happened the pass couple days I've been trying to use the Skywars Plugin.

What did you expect to happen?:I expected to forcestart a game to test my map and it would work easily.

What happened?: When I forcestart the game, the spawn for my Skywars map doesn't work. It basically just puts all the spawns I set into a normal world causing people to spawn in caves and oceans with their islands.

Any errors in console?:No
 / Bug / Crash:

**Comment by daboross** [comment]
Are there any errors in the console which happen when this happens?

**Comment by daboross** [comment]
Since it's been 15 days, I'm going to assume that either your error has been fixed, or you stopped using SkyWars. Either way, I can't fix the error without additional information.

If you are still experiencing the error, reply to this message, and I'll provide more help.
