### ISSUE TITLE
Skywars Plugin cant excecute functions

### ISSUE THREAD

**Issue by LokiDM** [SkyWars/SkyWars#223]
#### Issue / Bug / Crash:

Server Version:

When did this issue occur?:
After i started importing new maps into my server (sorry if i have bad english)
What did you expect to happen?:

What happened?:
Skywars plugin cannot excecute commands and when i type /help skywars it show me: skywars: null
                                                                                                                                   skywarssetup: null
Output url from `/sw report`:
Detailed:
When i imported the 1st map, and entered the server it did that, after a restart (server shutdown) it was ok. Then i imported the 2nd map, and it did not work until i deleted the world and the things in the worlds files (i mean in the sky wars folder), and i just tough it was the map that was causing problems, then after the 3rd map it just didnt work no matter what i tried. Please help, i love your plugin and i think its very well made and extremely useful 
NB: I have imported these maps before, same plugin, except ive added some new plugins.
Thelist of plugins i use:
Custom Enchantments
DungeonsXL
EmptyWorldGenerator
Essentials
LoginSecurity
Multiverse
PermissionsEx (PeX)
Player Vaults
Shopkeepers
Skins Restorer
Skywars (Your plugin)
Any errors in console?:
The first time yes, second and third no.

#### Feature Request:

What would you like to be added?:
I find the plugin very good but i have trouble when setting up things in lobby of skywars, i would like an explenation of how to run multiple games, and how to make players before the start of the game be up in those glass cages. Thank you in advance (again sorry for my bad english)

**Comment by daboross** [comment]
Thank you for the report!

Could you get a copy of the startup log for your server? That would show me what error is causing SkyWars to not work.

**Comment by LokiDM** [comment]
[2016-07-16-7.log.gz](https://github.com/SkyWars/SkyWars/files/368021/2016-07-16-7.log.gz)
Hello, sorry for replying so late, if you need any more info contact me

**Comment by daboross** [comment]
It's fine, looking at that no!

**Comment by daboross** [comment]
Seems like the kits.yml file has some errors - that's what's causing SkyWars to not start. If you post it, I can help.

**Comment by LokiDM** [comment]
Nah Ill just delete that file dont have any special kits, thanks.

**Comment by daboross** [comment]
Ok, sounds good!

If that doesn't work, just reply again and I'll see if there isn't something else I can do to help.
