### ISSUE TITLE
SkyWars doesn't work and appears red in /plugins after chests.yml is changed

### ISSUE THREAD

**Issue by MiniCraft12** [SkyWars/SkyWars#226]
#### Issue / Bug / Crash:

Server Version:
spigot-1.10.2-R0.1-SNAPSHOT-latest.jar

When did this issue occur?:
It occurred after I added some items to the chests.yml file.

What did you expect to happen?:
I expected SkyWars to work as normal.

What happened?:
SkyWars refused to start up and appeared red in /plugins. No commands work either.

Output url from `/sw report`:
Cant use /sw report.

Any errors in console?:
Not that I could find.
[chests.yml.zip](https://github.com/SkyWars/SkyWars/files/380442/chests.yml.zip)

**Comment by daboross** [comment]
Seems the last character of your `chests.yml` file is a "tab" character. Tabs aren't allowed in YML files, and this is what is causing your error.

Just delete the last space/tab from the file, on the end of the last line, and it should work.

**Comment by MiniCraft12** [comment]
Ok thanks, it is working now.

**Comment by daboross** [comment]
Awesome, glad it works! I'm closing this issue now.
