### ISSUE TITLE
Inven cleared

### ISSUE THREAD

**Issue by Hcurt** [SkyWars/SkyWars#228]
#### Issue / Bug / Crash: Players inventory gets cleared before joining, they come back and its gone

Server Version: 1.10

When did this issue occur?: on first download

What did you expect to happen?: not to clear the inventory...?

What happened?: Players inventory gets cleared 

Output url from `/sw report`: https://is.gd/TEgu39

Any errors in console?: 
http://pastebin.com/hEb6aKtw

#### Feature Request: a place in config to edit if it will clear inv or not for servers with plugins like PerWorldInventory

What would you like to be added?: NOTHING! YOUR PERFECT! (other than the inven getting cleared)

**Comment by daboross** [comment]
Ah sorry, there should definitely be a better error message here. I'll try and fix this in the next version.

For now, all you should need to do to fix this is use `/sw setlobby` in your lobby location. The error is, in a very indirect manner, saying that you don't have a lobby location set.

**Comment by Hcurt** [comment]
found that out, fixed but theres still the second error under that

**Comment by daboross** [comment]
Yeah, that error is also a bug that will be fixed - it shouldn't cause any actual problems though besides the error showing up in the console.

**Comment by Hcurt** [comment]
Its the only one other than mcmmo spamming console

**Comment by daboross** [comment]
I'll be sure to release a fix for it as soon as I fix the rest of the bugs reported directly for v2.2.0. In the meantime if you want a dev build with fixes for just these two bugs, here's a direct download for the last dev build:

https://51-11960663-gh.circle-artifacts.com/0//tmp/circle-artifacts.ZEMc8g7/SkyWars.jar

**Comment by Hcurt** [comment]
Are we able to make/add our own maps?
and set the teleporting places for players like this:
/sw add <map number> 
and it will set that position as the starting point of the game, looking at the world name too, or adding it to SkyWarsArenaWorld with something like /sw worldcreate <map number>
and if the /sw add <map number>, and 2 positions are indifferent worlds, make it say an error like , "must me in same world as <world of other position>" 
and the chests with /sw addchest <map number>

**Comment by daboross** [comment]
There is a system for building your own map, but it doesn't work exactly like that.

The way SkyWars works is that you can build a map "template" anywhere, and use the "/sws" command to save it - then SkyWars creates arena .blocks and .yml files for your arena, and you can add it to your configuration the same way skyblock-warriors and water-warriors are.

The chest contents will by default be whatever you put in the chests before saving it, with an optional chest randomizer enabled in the .yml arena config.

Check out https://dabo.guru/projects/skywars/creating-an-arena for a guide on how to save your own arena, and for more details.

**Comment by Hcurt** [comment]
I don't know how to use it

**Comment by daboross** [comment]
The guide should have followable steps, but I might have designed it a bit confusingly. Where are you getting stuck?
