### ISSUE TITLE
Disabled

### ISSUE THREAD

**Issue by jakovkacan** [SkyWars/SkyWars#245]
#### Issue / Bug / Crash:

Server Version: 1.11.2

When did this issue occur?: I joined the server and it was disabled (In plugin list it was red)

What did you expect to happen?: I don't know

What happened?:  Friend and I played some rounds of SkyWars and then we finished, I then re-joined later and saw that it is disabled

Output url from `/sw report`: I can't access that command (When you type it nothing happens.)

Any errors in console?: No

**Comment by daboross** [comment]
Hm, I'll see if I can reproduce this.

There should be _some_ error message if the plugin has been disabled. Could you possibly upload a log of your server starting to http://gist.github.com/ and reply with the link?

**Comment by jakovkacan** [comment]
Hi!
It looks like I fixed the problem. The problem happend when I changed save-inventory and save-exp on config to false. I dont know why this happend but now it is all fine :) Thank you so much for your time and for good support !

**Comment by daboross** [comment]
ok, thanks for the update!

I haven't been providing the _best_ support lately, but I'm glad you like the plugin!
