### ISSUE TITLE
Chest's don't work

### ISSUE THREAD

**Issue by IsaiahPatton** [SkyWars/SkyWars#249]
#### Issue / Bug / Crash:

Server Version: 1.12

When did this issue occur?: Every time map is played.

What did you expect to happen?: Chests would have items in them.

What happened?: Chests empty

Output url from `/sw report`:
https://gist.github.com/anonymous/bef6a1fdeeb0e6acf3ff9fc4627e0140

Any errors in console?:
No.

EDIT: related: #241  #242

**Comment by daboross** [comment]
assuming you didn't put any items in the chests when configuring the arena, I recommend replacing all instances of `randomize: false` with `randomize: true` in all files in `plugins/SkyWars/arenas/`

**Comment by IsaiahPatton** [comment]
fixed.
