### ISSUE TITLE
SkyWars doesn't work and appears red in /plugins after chests.yml is changed

### ISSUE THREAD

**Issue by Cqspa** [SkyWars/SkyWars#260]
#### Issue / Bug / Crash:

Server Version: 1.8

When did this issue occur?: Not to long ago

What did you expect to happen?: No

What happened?: well it was working perfectly then I decided to change my config file because I wanted it to be OP skywars and when I did it and saved the config file skywars just never worked again.

Output url from `/sw report`:

Any errors in console?: I don't knock

#### Feature Request:

This is the entire config

levels:
  level-1:
    item-value: 1
    chance: 35
  level-2:
    item-value: 3
    chance: 35
  level-3:
    item-value: 5
    chance: 10
  level-4:
    item-value: 7
    chance: 5
  level-5:
    item-value: 10
    chance: 15
items:
  level-1:
  - type: WOOD_SWORD
  - type: LEATHER_HELMET
  - type: LEATHER_CHESTPLATE
  - type: LEATHER_LEGGINGS
  - type: LEATHER_BOOTS
  - type: PORK, amount: 3
  - {type: RAW_FISH, amount: 3}
  - {type: APPLE, amount: 3}
  - {type: ARROW, amount: 7}
  level-2:
  - type: WOOD_SWORD
  - type: GOLD_HELMET
  - type: GOLD_CHESTPLATE
  - type: GOLD_LEGGINGS
  - type: GOLD_BOOTS
  - type: MUSHROOM_SOUP
  - {type: GRILLED_PORK, amount: 3}
  - {type: BOWL, amount: 4}
  - {type: APPLE, amount: 2}
  - {type: RAW_BEEF, amount: 4}
  - {type: COOKED_BEEF, amount: 2}
  - {type: RAW_CHICKEN, amount: 4}
  - {type: COOKED_CHICKEN, amount: 2}
  - {type: ENDER_PEARL, amount: 2}
  level-3:
  - type: IRON_HELMET
  - type: IRON_CHESTPLATE
  - type: IRON_LEGGINGS
  - type: IRON_BOOTS
  - type: GOLD_SWORD
  - type: CHAINMAIL_HELMET
  - type: CHAINMAIL_CHESTPLATE
  - type: CHAINMAIL_BOOTS
  - {type: MELON_BLOCK, amount: 4}
  - {type: GOLDEN_APPLE, amount: 2}
  - type: FLINT_AND_STEEL
  - type: GOLD_SWORD
  level-4:
  - type: IRON_SWORD
  level-5:
  - type: DIAMOND_SWORD
  - type: DIAMOND_HELMET
  - type: DIAMOND_CHESTPLATE
  - type: DIAMOND_LEGGINGS
  - type: DIAMOND_BOOTS
  - {type: CAKE, amount: 2}

**Comment by daboross** [comment]
There doesn't seem anything inherently wrong with that config.

Were there any console errors? Those are the most helpful.

**Comment by Cqspa** [comment]
Ill check right now! Thanks

**Comment by Cqspa** [comment]
What am I looking for?

**Comment by daboross** [comment]
If you want, uploading all of the log from when the server started to when the startup finished to https://gist.github.com/ would be good. I can look through for errors and information that way.

Otherwise, any error stacktraces with SkyWars associated with it, or just whatever text was before "Disabling SkyWars". Might be "SkyConfigurationException" or something else, but generally there's some stacktrace before the plugin is disabled.

**Comment by Cqspa** [comment]
Okay thanks sorry for a late repley

**Comment by Cqspa** [comment]
I cannot do it because its like a website and I cannot download it but if you want I just copied the entire log so here it is

10.01 19:03:36 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
10.01 19:03:36 [Server] INFO at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source) ~[?:?]
10.01 19:03:36 [Server] INFO at me.proxygames.powertool.EventHandlers.ClickEvent(EventHandlers.java:43) ~[?:?]
10.01 19:03:36 [Server] INFO at me.proxygames.powertool.check.clickevent.CheckClick(clickevent.java:39) ~[?:?]
10.01 19:03:36 [Server] INFO at me.proxygames.powertool.check.clickevent.fixcall(clickevent.java:53) ~[?:?]
10.01 19:03:36 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
10.01 19:03:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
10.01 19:03:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
10.01 19:03:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
10.01 19:03:36 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:18) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1227) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PWPTimedRegisteredListener.callEvent(PWPTimedRegisteredListener.java:28) [PerWorldPlugins.jar:?]
10.01 19:03:36 [Server] INFO at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:36 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
10.01 19:03:36 [Server] INFO org.bukkit.event.EventException
10.01 19:03:36 [Server] INFO Could not pass event PlayerInteractEvent to PowerToolsPlus v1.0.1
10.01 19:03:36 [Server] ERROR **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
10.01 19:03:36 [Multicraft] Skipped 431 lines due to rate limit (30/s)
10.01 19:03:34 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
10.01 19:03:34 [Server] INFO at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source) ~[?:?]
10.01 19:03:34 [Server] INFO at me.proxygames.powertool.EventHandlers.ClickEvent(EventHandlers.java:43) ~[?:?]
10.01 19:03:34 [Server] INFO at me.proxygames.powertool.check.clickevent.CheckClick(clickevent.java:39) ~[?:?]
10.01 19:03:34 [Server] INFO at me.proxygames.powertool.check.clickevent.fixcall(clickevent.java:53) ~[?:?]
10.01 19:03:34 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
10.01 19:03:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
10.01 19:03:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
10.01 19:03:34 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
10.01 19:03:34 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:18) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1227) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PWPTimedRegisteredListener.callEvent(PWPTimedRegisteredListener.java:28) [PerWorldPlugins.jar:?]
10.01 19:03:34 [Server] INFO at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:03:34 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
10.01 19:03:34 [Server] INFO org.bukkit.event.EventException
10.01 19:03:34 [Server] INFO Could not pass event PlayerInteractEvent to PowerToolsPlus v1.0.1
10.01 19:03:34 [Server] ERROR **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
10.01 19:03:31 [Server] INFO Message broadcasted by repeater
10.01 19:03:31 [Server] INFO Have Fun!
10.01 19:02:53 [Server] INFO default: Cqspa, Traime, Windchillx
10.01 19:02:53 [Multicraft] Skipped 408 lines due to rate limit (30/s)
10.01 19:02:45 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
10.01 19:02:45 [Server] INFO at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source) ~[?:?]
10.01 19:02:45 [Server] INFO at me.proxygames.powertool.EventHandlers.ClickEvent(EventHandlers.java:43) ~[?:?]
10.01 19:02:45 [Server] INFO at me.proxygames.powertool.check.clickevent.CheckClick(clickevent.java:39) ~[?:?]
10.01 19:02:45 [Server] INFO at me.proxygames.powertool.check.clickevent.fixcall(clickevent.java:53) ~[?:?]
10.01 19:02:45 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
10.01 19:02:45 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
10.01 19:02:45 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
10.01 19:02:45 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
10.01 19:02:45 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:18) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1227) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PWPTimedRegisteredListener.callEvent(PWPTimedRegisteredListener.java:28) [PerWorldPlugins.jar:?]
10.01 19:02:45 [Server] INFO at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:45 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
10.01 19:02:45 [Server] INFO org.bukkit.event.EventException
10.01 19:02:45 [Server] INFO Could not pass event PlayerInteractEvent to PowerToolsPlus v1.0.1
10.01 19:02:45 [Server] ERROR **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
10.01 19:02:38 [Server] INFO Armes4 left the game.
10.01 19:02:38 [Disconnect] User Armes4 has disconnected, reason: Disconnected
10.01 19:02:38 [Multicraft] Skipped 629 lines due to rate limit (30/s)
10.01 19:02:36 [Server] INFO at me.proxygames.powertool.EventHandlers.ClickEvent(EventHandlers.java:43) ~[?:?]
10.01 19:02:36 [Server] INFO at me.proxygames.powertool.check.clickevent.CheckClick(clickevent.java:39) ~[?:?]
10.01 19:02:36 [Server] INFO at me.proxygames.powertool.check.clickevent.fixcall(clickevent.java:53) ~[?:?]
10.01 19:02:36 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
10.01 19:02:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
10.01 19:02:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
10.01 19:02:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
10.01 19:02:36 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:18) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1227) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
10.01 19:02:36 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PWPTimedRegisteredListener.callEvent(PWPTimedRegisteredListener.java:28) [PerWorldPlugins.jar:?]

**Comment by daboross** [comment]
Thank you!

I don't think this particular error is what is stopping SkyWars, but maybe if we can fix it we can see why SkyWars is erroring.

The error seems to be a plugin PowerToolsPlus only supporting Minecraft versions 1.9+. It accesses the 'getHand' method, which does not exist before Spigot 1.9.

Could you try disabling or removing PowerToolsPlus  and seeing if there are other errors that might have been drowned out by its errors?

**Comment by Cqspa** [comment]
Okay thanks Ill see if that works thanks so far

**Comment by Cqspa** [comment]
I made a script and added it to the skywars config so it works now but thank you so much for taking your time to help me! Wish you luck for the future!

**Comment by daboross** [comment]
Alright, glad it's working.

As a note that last thing wasn't meant to fix _skywars itself_, but just hoping to get the skywars errors more obvious.

Best of luck to you as well!
