### ISSUE TITLE
There is no sky wars arena world, it won't let me do any command skywars related.

### ISSUE THREAD

**Issue by Trefala** [SkyWars/SkyWars#267]
#### Issue / Bug / Crash: No sky wars arena world is created after i backed up my server. This caused all sky wars commands to not work including /sw report.

Server Version: 1.12.2 Spigot

When did this issue occur?: After I backed up my server the sky wars arena world wouldn't appear, then I tried to re download the plugin but it still wouldn't work, even after i reloaded, and stopped and started the server.

What did you expect to happen?: I thought after I backed up my server the sky wars arena world would be there and everything would be fine.

What happened?: Nothing in the sky wars plugin worked afterward and I don't know what to do next. 

Output url from `/sw report`: None, /sw report doesn't work just comes up with an internal error occurred, same with every other command in the plugin. It just comes up with plugin disabled in the console. 

Any errors in console?: No errors just comes up with plugin disabled in the console.

#### Feature Request:

What would you like to be added?:

**Comment by daboross** [comment]
If the plugin is disabled then something happened when the server started up. Could you upload or paste in a server startup log?

**Comment by Trefala** [comment]
went to make a github account and then realize i already made one and apparently i did this, very interesting
