### ISSUE TITLE
chests not filling up in a new arena?

### ISSUE THREAD

**Issue by GoldenCookieGIT** [SkyWars/SkyWars#273]
#### Issue / Bug / Crash:

Server Version: 1.12.2

When did this issue occur?: everytime i spawn into my arena

What did you expect to happen?:the chests on the map to fill up

What happened?:the chests dont fill up

Output url from `/sw report`:no

Any errors in console?:no

#### Feature Request:

What would you like to be added?:no

**Comment by ItayKisous** [comment]
You have to go to your arenaname.yml and enable the randomizer for each chest
