### ISSUE TITLE
Non-op players can´t use kits

### ISSUE THREAD

**Issue by Elivell** [SkyWars/SkyWars#277]
#### Issue / Bug / Crash:

Server Version: spigot 1.8

When did this issue occur?: today

What did you expect to happen?: i expected the kit gui to pop up

What happened?: when my friend used /sw kit gui it says: you don´t have permission to do that

Output url from `/sw report`:

Any errors in console?: no

#### Feature Request: N/a

What would you like to be added?: N/a

**Comment by daboross** [comment]
Make sure you grant all users the `skywars.kit` permission with your permissions system. Depending on what system you have, I might or might not be able to help you do that?

See https://dabo.guru/projects/skywars/commands-and-permissions
