### ISSUE TITLE
Players not dying from falling into void.

### ISSUE THREAD

**Issue by Xyrophlex** [SkyWars/SkyWars#66]
Hi there,
I downloaded the plugin for Skywars yesterday for my server, but after testing it out, we realized that we just couldn't...die. I may be setting the regions wrong - though I have captured the arena, do I need to go to the very bottom of the world for the second setpos? I can include server details if needed.
Thanks,
Xyrophlex

**Comment by BenPlaysMC** [comment]
I want to know the plugin! I'm having the same problem!
