### ISSUE TITLE
LeaderBoard System in-game and webstats?

### ISSUE THREAD

**Issue by Zuhaib231** [SkyWars/SkyWars#69]
Hi, your plugin is the easiest to use and is overall a great plugin but would it be possible to add scoreboards and a leaderboard system with points that get updated on signs in-game, maybe even player heads that get updated according to the signs, also, could you also add a webstat system (mysql, php, etc...) that also shows the points and maybe kills. People can search themselves or other players. An example which I have used would be this plugin,  
http://dev.bukkit.org/bukkit-plugins/survival-games/
It would be really good to put on server websites that allow viewing of stats and add a more competitive fell in-game.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

This has now been fully added, and will be released with the next release (either 2.1.2 or 2.2.0). Not completely fully, but there is now a leaderboard command.

**Comment by daboross** [comment]
As a leaderboard top 10 API and command have been implemented, I'm going to move the priority of this issue (now representing head/sign system) to a later version

**Comment by daboross** [comment]
I'm going to close this as the issue for actually having a leaderboard system, and have two branching issues for head/sign system and scoreboard integration. https://github.com/SkyWars/SkyWars/issues/200 is now for head/sign system, https://github.com/SkyWars/SkyWars/issues/199 is now for scoreboard system!

If you are still using this plugin, leaderboards do now exist in the next update, but not head/sign or scoreboard integration.
