### ISSUE TITLE
Inventories

### ISSUE THREAD

**Issue by soaringeg127** [SkyWars/SkyWars#80]
I have noticed that once somebody wins the match, or wherever somebody dies and their items hit the ground, the items are saved and when they join back into another game the items will be in the inventories / on the ground. My skywars version is 1.4.2.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work - this should be fixed as of https://github.com/SkyWars/SkyWars/commit/73d2f8bffbfd1ae34d8b98d9d78aaf4596a2ca6a.
